### ISSUE TITLE
Top bar stays on lupa toggle off

### ISSUE THREAD

**Issue by UziTech** [hex13/atom-lupa#22]
When lupa is open and `atom-lupa:toggle` is executed the side panel disappears but the bread crumbs on the top stay

![lupa](https://cloud.githubusercontent.com/assets/97994/16093943/8f71ec94-3303-11e6-81dc-3962dd4b3ce2.gif)

**Comment by hex13** [comment]
Ok, I updated package to toggle also breadcrumbs. https://github.com/hex13/atom-lupa/commit/5de4dc6983297129d9305f26af779dca078a6cc5

**Comment by pmachart** [comment]
when i asked for a toggle keybind in #17 i didn't want it to hide the breadcrumbs, just the sidebar :(

**Comment by hex13** [comment]
https://xkcd.com/1172/ ;)

But I see. Maybe we need two commands 1. toogle sidepanel, 2. toggle breadcrumbs.
But we would need then third command "toggle whole lupa" :/

I wonder if it would be a little overengineered...

**Comment by hex13** [comment]
Or maybe behavior of "what toggle Lupa command does" should be configurable by settings?

**Comment by pmachart** [comment]
was going to suggest that :)

**Comment by hex13** [comment]
Ok. Done. There is a config option `breadcrumbsAlwaysVisible`:
![image](https://cloud.githubusercontent.com/assets/3883359/16319867/3b57dd38-3995-11e6-903d-1fd5b1a29146.png)
when active, breadcrumbs will not hide even when toggling.
