### ISSUE TITLE
Get rid of the "Made by hex13"

### ISSUE THREAD

**Issue by ProLoser** [hex13/atom-lupa#25]
We get it. You don't have to waste screen space for the sake of advertising yourself. I can't even turn this off? Can't you just make it show up as a modal upon first install and then drop it? Doesn't need to be so intrusive.

**Comment by ProLoser** [comment]
And while we're at it, you shouldn't hard-code the instructions on how to use the package permanently. I mean, if people REALLY forget a lot, make it a tooltip that appears when you focus the input box. You can even have the 'index' button take the place of the input box if the searching doesn't work until you've indexed.

**Comment by hex13** [comment]
You're right that these things take too much vertical space, so I threw them out.
