### ISSUE TITLE
Warnings should be optional (or removed entirely)

### ISSUE THREAD

**Issue by ProLoser** [hex13/atom-lupa#31]
They take up precious real estate, and some of these warnings are extremely opinionated and I may choose to never address them. I may have a really long function and I can't or won't ever do anything about it, so I should not be forced to lose visual real estate. You've provided no way to toggle this stuff off or adjust it. And frankly, this doesn't even seem like the responsibility of YOUR package, it's just causing bloat and complexity.

If you REALLY want to provide intuitive linting in symbol view (which I don't really think is necessary since I can see linting errors in my scrollbar, gutter, and minimap) then you should instead simply count how many linter errors and warnings are in each function, etc, and simply give me a warning or error icon on the symbol that contains such issues with a count of how many errors or warnings are found.

However, I ultimately feel this entire feature just needs to be removed. Completely superfluous and not worth the time to work on since it's done in such a limited manner.

**Comment by hex13** [comment]
Now warnings are optional and can be disabled/enabled in settings (thanks to @srguiwiz )
