### ISSUE TITLE
Add toggle side function 

### ISSUE THREAD

**Issue by satianoCantana** [hex13/atom-lupa#42]
Please add a toggle side (left right) function like the one in the tree view package.

**Comment by hex13** [comment]
![image](https://cloud.githubusercontent.com/assets/3883359/25189938/03d59670-252b-11e7-9996-983b1eb351f1.png)
Ok. I made setting for choosing on which side Lupa panel should appear (it requires restart Atom after changing)

**Comment by satianoCantana** [comment]
Sweet, how do I turn it on ? I ' ve already updated the package but can't find the option.
Do I need to configure something in the atomLupa.json file?

**Comment by satianoCantana** [comment]
My bad, found it Thanks
