### ISSUE TITLE
TextEditor.editorElement is deprecated.

### ISSUE THREAD

**Issue by bay0** [hex13/atom-lupa#47]
`TextEditor.prototype.editorElement` has always been private, but now
it is gone. Reading the `editorElement` property still returns a
reference to the editor element but this field will be removed in a
later version of Atom, so we recommend using the `element` property instead.
```
TextEditor.editorElement (<embedded>:2381:20)
atomSetPosition (/Users/bayram/.atom/packages/atom-lupa/lib/atom-bindings/middleware.js:5:24)
<unknown> (/Users/bayram/.atom/packages/atom-lupa/lib/atom-bindings/middleware.js:85:21)
<unknown> (/Users/bayram/.atom/packages/atom-lupa/lib/lupaMiddleware.js:89:9)
GoToTransformer.goTo (/Users/bayram/.atom/packages/atom-lupa/lib/middleware/domMiddleware.js:56:32)
GoToTransformer.dispatch (/Users/bayram/.atom/packages/atom-lupa/lib/middleware/domMiddleware.js:76:41)
```

**Comment by hex13** [comment]
On my installation*  `atom-lupa` threw exception in file `atom-lupa/lib/atom-bindings/middleware.js` (like in your stack trace) but in other place.

On my installation `editorElement` still exists and is equal to `element` (but I changed it to `element` anyway).

On the other hand `element.presenter` does not exist (I used presenter for this:
```
presenter.commitPendingScrollTopPosition();.
```
and this line threw an exception.

not sure what this was for, but probably for fixing some issues with Atom scrolling behavior.

Although it seems that even without this line `atom-lupa` scrolls properly, so I commented it.

*I haveAtom 1.19.1
